### ISSUE TITLE
cannot import name '_request_ctx_stack' 

### ISSUE THREAD

**Issue by ezbik** [jonalxh/Flask-Admin-Dashboard#18]
doesnt work

```
$ ./app.py 
Traceback (most recent call last):
  File "./app.py", line 5, in <module>
    from flask_security import Security, SQLAlchemyUserDatastore, \
  File "/home/z/tmp/Flask-Admin-Dashboard/venv/lib/python3.8/site-packages/flask_security/__init__.py", line 13, in <module>
    from .core import Security, RoleMixin, UserMixin, AnonymousUser, current_user
  File "/home/z/tmp/Flask-Admin-Dashboard/venv/lib/python3.8/site-packages/flask_security/core.py", line 18, in <module>
    from flask_babelex import Domain
  File "/home/z/tmp/Flask-Admin-Dashboard/venv/lib/python3.8/site-packages/flask_babelex/__init__.py", line 20, in <module>
    from flask import _request_ctx_stack
ImportError: cannot import name '_request_ctx_stack' from 'flask' (/home/z/tmp/Flask-Admin-Dashboard/venv/lib/python3.8/site-packages/flask/__init__.py)
```

**Comment by 202030481266** [comment]
Here is my requirments.txt, and it runs good in Ubuntu22.04 LTS.
```bash
Flask==2.1.3
Flask-Admin==1.6.1
Flask-SQLAlchemy==2.5.1
Flask-Security>=1.7.5
enum34==1.1.6
email_validator
Werkzeug==2.0.3
WTForms==2.3.0
Flask-WTF==1.2.1
SQLAlchemy==1.4
```

**Comment by 202030481266** [comment]
I have tried many times and test many version packages. The following requirments runs well in Ubuntu22.04 LTS.
![image](https://github.com/jonalxh/Flask-Admin-Dashboard/assets/73118494/4225c0a1-e3a6-450a-9531-61899fd0cb4b)
