### ISSUE TITLE
How to run this app.py in windows 10

### ISSUE THREAD

**Issue by soullessdead** [jonalxh/Flask-Admin-Dashboard#6]
using python app.py i have this error
```
(venv) C:\Users\Carlos Gonzalez\Flask-Admin-Dashboard>python app.py
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    from flask_security import Security, SQLAlchemyUserDatastore, \
  File "C:\Users\CARLOS~1\FLASK-~1\venv\lib\site-packages\flask_security\__init__.py", line 13, in <module>
    from .core import Security, RoleMixin, UserMixin, AnonymousUser, current_user
  File "C:\Users\CARLOS~1\FLASK-~1\venv\lib\site-packages\flask_security\core.py", line 24, in <module>
    from passlib.context import CryptContext
  File "C:\Users\CARLOS~1\FLASK-~1\venv\lib\site-packages\passlib\context.py", line 15, in <module>
    from passlib.registry import get_crypt_handler, _validate_handler_name
  File "C:\Users\CARLOS~1\FLASK-~1\venv\lib\site-packages\passlib\registry.py", line 12, in <module>
    from passlib.ifc import PasswordHash
  File "C:\Users\CARLOS~1\FLASK-~1\venv\lib\site-packages\passlib\ifc.py", line 10, in <module>
    from passlib.utils.decor import deprecated_method
  File "C:\Users\CARLOS~1\FLASK-~1\venv\lib\site-packages\passlib\utils\__init__.py", line 845, in <module>
    from time import clock as timer
ImportError: cannot import name 'clock' from 'time' (unknown location)
```
follow the steps, but i don't know how to run this app in os windows 10

any help?

**Comment by jonalxh** [comment]
Hi @soullessdead, I think it is a problem with python 3.8. Can you try with an older version? Maybe 3.6.

**Comment by navid-ka** [comment]
You will need to run it in docker with linux containers!
