### ISSUE TITLE
email_validator error

### ISSUE THREAD

**Issue by Serena123lasine** [jonalxh/Flask-Admin-Dashboard#9]
hi , i'm still beginner i want to test your script on my localhost , i use mac to run this project , i have only one issue, can i get some help , please ?
i try to install email_validator with this command pip install email_validator and nothing has change 

Thank u so much.

MacBook-Pro:Flask-Admin-Dashboard med$ ./app.py
Traceback (most recent call last):
  File "./app.py", line 5, in <module>
    from flask_security import Security, SQLAlchemyUserDatastore, \
  File "/Users/med/Desktop/sms/Flask-Admin-Dashboard/venv/lib/python2.7/site-packages/flask_security/__init__.py", line 13, in <module>
    from .core import Security, RoleMixin, UserMixin, AnonymousUser, current_user
  File "/Users/med/Desktop/sms/Flask-Admin-Dashboard/venv/lib/python2.7/site-packages/flask_security/core.py", line 28, in <module>
    from .forms import ChangePasswordForm, ConfirmRegisterForm, \
  File "/Users/med/Desktop/sms/Flask-Admin-Dashboard/venv/lib/python2.7/site-packages/flask_security/forms.py", line 69, in <module>
    email_validator = Email(message='INVALID_EMAIL_ADDRESS')
  File "/Users/med/Desktop/sms/Flask-Admin-Dashboard/venv/lib/python2.7/site-packages/wtforms/validators.py", line 332, in __init__
    raise Exception("Install 'email_validator' for email validation support.")
Exception: Install 'email_validator' for email validation support.

**Comment by jonalxh** [comment]
Hi. Are you using a virtualenv?

Have you tried `pip install wtforms[email]` or `pip install email-validator`?

**Comment by Serena123lasine** [comment]
i solved this issue , thank u again.
